# Generated by Django 3.2.25 on 2026-03-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0002_auto_20260225_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetHealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('note', models.TextField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_app.cattle')),
                ('vet_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='dairy_app.cattle')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_details', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('cattle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='dairy_app.cattle')),
            ],
        ),
    ]
