# Generated by Django 3.2.25 on 2026-03-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0003_treatment_vaccination_vethealthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='vethealthrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
