# Generated by Django 3.2.25 on 2026-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0004_vethealthrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vethealthrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
