# Generated by Django 3.2.25 on 2026-03-04 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0005_vethealthrecord_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
