# Generated by Django 3.2.25 on 2026-02-25 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dairy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='schedule_time',
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='feed_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='dairy_user_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='dairy_user_perms', to='auth.Permission'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
